name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # - name: configure
    #   run: ./configure

    - name: Install dependencies
      run: make install

    # - name: Run check
    #   run: make check

    # - name: Run distcheck
    #   run: make distcheck
    - name: Build
      run: make build
# pages
    - name: Setup Pages
      uses: actions/configure-pages@v3
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      with:
        # Upload entire repository
        path: '_site/'
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2
    
