name: Build & Deploy

on:
  push:
    branches: ["main"]
  #  pull_request:
  #    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  pages: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    environment:
      name: github-pages

      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # - name: configure
      #   run: ./configure

      #    - name: Install dependencies
      #      run: make install
      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: "npm"
      - run: npm ci
      - run: npm run build
      # - name: Run check
      #   run: make check

      # - name: Run distcheck
      #   run: make distcheck
      #    - name: Build
      #      run: make build
      # pages
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          # Upload build artifacts
          path: "_site/"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
